import { ChallengeItem, UniversityItem, ProjectItem, GrantItem } from '@/types';

export const INITIAL_UNIVERSITIES: UniversityItem[] = [
  {
    id: 'univ-1',
    name: 'BIT Mesra (Birla Institute of Technology)',
    code: 'BITM-RAN',
    district: 'Ranchi',
    state: 'Jharkhand',
    type: 'Deemed University',
    departments: ['Environmental Engineering', 'Water Resource Mgmt', 'Computer Science & AI', 'Renewable Energy', 'Biotechnology'],
    facultyCount: 220,
    studentCount: 5400,
    activeProjects: 14,
  },
  {
    id: 'univ-2',
    name: 'NIT Jamshedpur (National Institute of Technology)',
    code: 'NIT-JAM',
    district: 'East Singhbhum',
    state: 'Jharkhand',
    type: 'Institute of National Importance',
    departments: ['Civil & Structural Engg', 'Mechanical & Robotics', 'Metallurgical & Materials', 'Electrical & Smart Grid'],
    facultyCount: 180,
    studentCount: 4200,
    activeProjects: 18,
  },
  {
    id: 'univ-3',
    name: 'IIT ISM Dhanbad (Indian Institute of Technology)',
    code: 'IIT-DHN',
    district: 'Dhanbad',
    state: 'Jharkhand',
    type: 'Institute of National Importance',
    departments: ['Mining & Environmental Hydrogeology', 'Geophysics', 'Chemical & Applied Chemistry', 'Data Analytics'],
    facultyCount: 310,
    studentCount: 7800,
    activeProjects: 22,
  },
  {
    id: 'univ-4',
    name: 'Ranchi University (Central University Campus)',
    code: 'RU-RAN',
    district: 'Ranchi',
    state: 'Jharkhand',
    type: 'State University',
    departments: ['Botany & Agriculture Extension', 'Social Work & Tribal Dev', 'Public Health', 'Economics & Rural Dev'],
    facultyCount: 190,
    studentCount: 12500,
    activeProjects: 9,
  },
  {
    id: 'univ-5',
    name: 'Vinoba Bhave University',
    code: 'VBU-HZB',
    district: 'Hazaribagh',
    state: 'Jharkhand',
    type: 'State University',
    departments: ['Geology & Soil Conservation', 'Information Technology', 'Biotechnology'],
    facultyCount: 140,
    studentCount: 8900,
    activeProjects: 7,
  }
];

export const INITIAL_CHALLENGES: ChallengeItem[] = [
  {
    id: 'ch-101',
    title: 'High Arsenic & Lead Contamination in Groundwater Wells',
    description: 'Multiple hand pumps in Namkum panchayat tested positive for heavy metal contamination exceeding WHO safety standards. Rural school children & elders suffer chronic skin conditions and gastroenteritis. Immediate low-cost bio-filtration or solar distillation unit required.',
    category: 'Water Resources',
    subCategory: 'Heavy Metal Filtration & Testing',
    district: 'Ranchi',
    locationName: 'Namkum Village, Block-2',
    latitude: 23.3441,
    longitude: 85.3854,
    images: ['https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=800'],
    status: 'IN_PROGRESS',
    urgencyScore: 92,
    impactScore: 88,
    upvotesCount: 142,
    reporterName: 'Sunil Munda (Gram Pradhan)',
    submitterType: 'PANCHAYAT_PRI',
    submitterOrgId: 'PRI-LGD-23841',
    assignedUniversityId: 'univ-1',
    assignedUniversityName: 'BIT Mesra (Birla Institute of Technology)',
    createdAt: '2026-08-15T10:30:00Z',
  },
  {
    id: 'ch-102',
    title: 'Post-Harvest Paddy Storage Losses & Elephant Raid Warnings',
    description: 'Farmers in Latehar border villages lose up to 35% of harvested rice due to damp warehouse conditions and wild elephant attacks. Need IoT acoustic early warning sensors & solar-powered hermetic silo storage solution.',
    category: 'Sustainable Agriculture',
    subCategory: 'Crop Storage & Wildlife Protection',
    district: 'Latehar',
    locationName: 'Mahuadanr Panchayat',
    latitude: 23.4981,
    longitude: 84.1039,
    images: ['https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800'],
    status: 'IN_PROGRESS',
    urgencyScore: 86,
    impactScore: 90,
    upvotesCount: 98,
    reporterName: 'Anita Oraon (Farmer Cooperative)',
    submitterType: 'COMMUNITY_ORG',
    submitterOrgId: 'NGO-JH-882',
    assignedUniversityId: 'univ-2',
    assignedUniversityName: 'NIT Jamshedpur',
    createdAt: '2026-08-16T14:15:00Z',
  },
  {
    id: 'ch-103',
    title: 'Coal Mine Runoff Acidifying Local Irrigation Canals',
    description: 'Acid mine drainage (AMD) from abandoned open-cast coal pits is leeching into agricultural canals, rendering soil saline and infertile across 12 villages near Jharia.',
    category: 'Waste Management & Sanitation',
    subCategory: 'Industrial Mine Reclamation',
    district: 'Dhanbad',
    locationName: 'Jharia Coalfield Belt',
    latitude: 23.7516,
    longitude: 86.4170,
    images: ['https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800'],
    status: 'OPEN',
    urgencyScore: 94,
    impactScore: 95,
    upvotesCount: 215,
    reporterName: 'Dr. R.K. Mahto (Local Health Worker)',
    submitterType: 'GOVT_DEPARTMENT',
    submitterOrgId: 'GOVT-HEALTH-JH',
    assignedUniversityId: 'univ-3',
    assignedUniversityName: 'IIT ISM Dhanbad',
    createdAt: '2026-08-18T09:00:00Z',
  },
  {
    id: 'ch-104',
    title: 'Lack of Cold-Chain Logistics for Tribal Forest Honey & Mahua',
    description: 'Self Help Groups (SHGs) in Khunti harvest organic forest honey and medicinal herbs but spoilage and middleman exploitation cut their revenue by 60%. Need portable solar refrigeration units & mobile app block verification.',
    category: 'Rural Livelihoods & NTFP',
    subCategory: 'Tribal Livelihood Tech',
    district: 'Khunti',
    locationName: 'Torpa Block Forest Cooperative',
    latitude: 22.9837,
    longitude: 85.2801,
    images: ['https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=800'],
    status: 'VERIFIED',
    urgencyScore: 78,
    impactScore: 84,
    upvotesCount: 76,
    reporterName: 'Sushila Tirkey (SHG Lead)',
    submitterType: 'COMMUNITY_ORG',
    assignedUniversityId: 'univ-4',
    assignedUniversityName: 'Ranchi University',
    createdAt: '2026-08-19T11:45:00Z',
  },
  {
    id: 'ch-105',
    title: 'Unmonitored Municipal Waste Dumping near Subarnarekha River',
    description: 'Open illegal plastic waste dumping near riverbank causing toxic microplastic discharge into municipal water supply inlet.',
    category: 'Environment & Forestry',
    subCategory: 'River Cleaning & AI Drone Patrol',
    district: 'East Singhbhum',
    locationName: 'Jamshedpur Subarnarekha Basin',
    latitude: 22.8046,
    longitude: 86.2029,
    images: ['https://images.unsplash.com/photo-1621451537084-482c73073a0f?w=800'],
    status: 'OPEN',
    urgencyScore: 85,
    impactScore: 89,
    upvotesCount: 165,
    reporterName: 'Vikram Singh (Ward Commissioner)',
    submitterType: 'URBAN_LOCAL_BODY',
    submitterOrgId: 'ULB-JSR-04',
    assignedUniversityId: 'univ-2',
    assignedUniversityName: 'NIT Jamshedpur',
    createdAt: '2026-08-20T16:20:00Z',
  },
  {
    id: 'ch-106',
    title: 'Frequent Power Outages at Primary Health Centers (PHCs) disrupting Vaccine Storage',
    description: 'Remote health sub-centers in Simdega experience 10+ hours daily grid power failures. Temperature-sensitive maternal vaccines spoiled during summer months.',
    category: 'Rural Healthcare',
    subCategory: 'Solar Microgrid & Telemedicine',
    district: 'Simdega',
    locationName: 'Bano Primary Health Clinic',
    latitude: 22.6180,
    longitude: 84.9750,
    images: ['https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800'],
    status: 'IN_PROGRESS',
    urgencyScore: 96,
    impactScore: 98,
    upvotesCount: 310,
    reporterName: 'Dr. Mary Ekka (ANM Officer)',
    submitterType: 'GOVT_DEPARTMENT',
    assignedUniversityId: 'univ-1',
    assignedUniversityName: 'BIT Mesra',
    createdAt: '2026-08-21T08:10:00Z',
  }
];

export const INITIAL_PROJECTS: ProjectItem[] = [
  {
    id: 'proj-501',
    title: 'Jal-Shuddhi: Solar Graphene Bio-Filter for Heavy Metal Water Purification',
    description: 'A low-cost ₹4,500 portable graphene and coconut husk bio-filtration unit capable of filtering 200L/day arsenic-free drinking water.',
    challengeId: 'ch-101',
    challengeTitle: 'High Arsenic & Lead Contamination in Groundwater Wells',
    universityId: 'univ-1',
    universityName: 'BIT Mesra',
    facultyMentorName: 'Dr. Bindhu Lal (Professor & Head, Civil & Environmental Engg)',
    targetDepartment: 'Civil & Environmental Engineering',
    teamName: 'Team Jal-Rakshak (BIT Mesra Innovators)',
    teamMembers: ['Aarav Sharma (B.Tech 4th Yr)', 'Priya Hansda (M.Tech Water Mgmt)', 'Rohan Verma (Research Scholar)'],
    nepCreditType: 'CAPSTONE',
    nepCreditsCount: 4,
    billOfMaterials: 'Coconut husk bio-char, Graphene membrane, ESP32 Turbidity Sensor, Solar 50W',
    status: 'PILOT_TESTING',
    budgetRequired: 350000,
    budgetFunded: 350000,
    patentStatus: 'APPLIED',
    milestones: [
      { id: 'm-1', title: 'Lab Water Sample Testing & Chemical Profiling', dueDate: '2026-08-01', status: 'COMPLETED', deliverables: 'NABL Certified Lab Report' },
      { id: 'm-2', title: 'Graphene Filter Core Prototype Build', dueDate: '2026-08-15', status: 'COMPLETED', deliverables: 'Working Prototype Unit v1.2' },
      { id: 'm-3', title: 'Field Pilot Deployment in 3 Namkum Schools', dueDate: '2026-09-10', status: 'IN_PROGRESS', deliverables: 'Real-time Sensor Monitoring Feed' },
      { id: 'm-4', title: 'Provisional Patent Application Filing', dueDate: '2026-09-30', status: 'PENDING' }
    ],
    createdAt: '2026-08-16T12:00:00Z',
  },
  {
    id: 'proj-502',
    title: 'Solar IoT Elephant Warning & Hermetic Paddy Silos (Gaja-Guard)',
    description: 'Geofenced seismic motion sensors and acoustic alarms linked to solar hermetic silos to safeguard rice harvests in Latehar villages.',
    challengeId: 'ch-102',
    challengeTitle: 'Post-Harvest Paddy Storage Losses & Elephant Raid Warnings',
    universityId: 'univ-2',
    universityName: 'NIT Jamshedpur',
    facultyMentorName: 'Prof. Danish Ali Khan (Head, Computer Science & Engg)',
    targetDepartment: 'Computer Science & Engineering',
    teamName: 'AgriTech Pioneers',
    teamMembers: ['Karan Mehta', 'Neha Kumari', 'Siddharth Munda'],
    nepCreditType: 'INTERNSHIP',
    nepCreditsCount: 3,
    billOfMaterials: 'Seismic Geophone sensors, Solar Battery 100Ah, Siren horn 120dB',
    status: 'PROTOTYPING',
    budgetRequired: 480000,
    budgetFunded: 250000,
    patentStatus: 'NONE',
    milestones: [
      { id: 'm-201', title: 'Seismic Sensor Field Calibration', dueDate: '2026-08-20', status: 'COMPLETED' },
      { id: 'm-202', title: 'Solar Hermetic Container Fabrication', dueDate: '2026-09-05', status: 'IN_PROGRESS' },
      { id: 'm-203', title: 'Village Co-op Mobile App Integration', dueDate: '2026-09-25', status: 'PENDING' }
    ],
    createdAt: '2026-08-17T15:30:00Z',
  },
  {
    id: 'proj-503',
    title: 'Surya-Health: Thermal Storage Solar Microgrid for PHC Vaccine Coolers',
    description: 'Phase-change material (PCM) hybrid solar battery bank ensuring zero interruption 2-8°C cold chain for rural PHC vaccination centers.',
    challengeId: 'ch-106',
    challengeTitle: 'Frequent Power Outages at Primary Health Centers',
    universityId: 'univ-1',
    universityName: 'BIT Mesra',
    facultyMentorName: 'Dr. Kunal Mukhopadhyay (Head, Bioengineering & Biotech)',
    targetDepartment: 'Bioengineering & Biotechnology',
    teamName: 'MedTech Solvers',
    teamMembers: ['Abhishek Roy', 'Divya Singh', 'Manish Ekka'],
    nepCreditType: 'CAPSTONE',
    nepCreditsCount: 4,
    billOfMaterials: 'Phase-Change Material PCM wax, Solar Inverter 2kVA, Temp Logger IoT',
    status: 'APPROVED',
    budgetRequired: 600000,
    budgetFunded: 600000,
    patentStatus: 'APPLIED',
    milestones: [
      { id: 'm-301', title: 'PCM Thermal Storage Integration Test', dueDate: '2026-08-25', status: 'IN_PROGRESS' },
      { id: 'm-302', title: 'Simdega Health Center Installation', dueDate: '2026-09-15', status: 'PENDING' }
    ],
    createdAt: '2026-08-22T09:00:00Z',
  }
];

export const INITIAL_GRANTS: GrantItem[] = [
  {
    id: 'g-1',
    projectId: 'proj-501',
    projectTitle: 'Jal-Shuddhi: Solar Graphene Bio-Filter',
    sponsorName: 'Tata Steel Foundation (CSR)',
    amountPledged: 350000,
    status: 'DISBURSED',
    csrCategory: 'Clean Drinking Water & Rural Sanitation',
    createdAt: '2026-08-17T10:00:00Z',
  },
  {
    id: 'g-2',
    projectId: 'proj-502',
    projectTitle: 'Solar IoT Elephant Warning & Hermetic Silos',
    sponsorName: 'Coal India Limited (CIL CSR Fund)',
    amountPledged: 250000,
    status: 'COMMITTED',
    csrCategory: 'Rural Livelihood & Agriculture Support',
    createdAt: '2026-08-19T14:30:00Z',
  },
  {
    id: 'g-3',
    projectId: 'proj-503',
    projectTitle: 'Surya-Health: Thermal Storage Solar Microgrid',
    sponsorName: 'NTPC Renewable Energy CSR Trust',
    amountPledged: 600000,
    status: 'DISBURSED',
    csrCategory: 'Healthcare Infrastructure & Solar Energy',
    createdAt: '2026-08-22T16:00:00Z',
  }
];

export const DISTRICT_STATS = [
  { district: 'Ranchi', submitted: 42, activeProjects: 8, resolved: 14, csrFunded: '₹ 24.5 Lakhs' },
  { district: 'East Singhbhum', submitted: 38, activeProjects: 7, resolved: 11, csrFunded: '₹ 18.0 Lakhs' },
  { district: 'Dhanbad', submitted: 51, activeProjects: 9, resolved: 16, csrFunded: '₹ 32.0 Lakhs' },
  { district: 'Hazaribagh', submitted: 29, activeProjects: 4, resolved: 8, csrFunded: '₹ 12.5 Lakhs' },
  { district: 'Latehar', submitted: 24, activeProjects: 5, resolved: 6, csrFunded: '₹ 15.0 Lakhs' },
  { district: 'Khunti', submitted: 19, activeProjects: 3, resolved: 5, csrFunded: '₹ 9.0 Lakhs' },
  { district: 'Simdega', submitted: 22, activeProjects: 4, resolved: 4, csrFunded: '₹ 11.0 Lakhs' },
  { district: 'Bokaro', submitted: 31, activeProjects: 6, resolved: 10, csrFunded: '₹ 19.5 Lakhs' }
];
